package org.openmrs.module.financials;

public class ConvulsiveDiagnosisConstants {

    public static final String CONVULSIVE1="206AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE2="110191AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE3="110664AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE4="110815AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE5="110818AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE6="112353AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE7="113054AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE8="114180AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE9="117849AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE10="117858AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE11="118580AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE12="123550AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE13="124958AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE14="126474AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE15="129948AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE16="138960AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE17="140339AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE18="140485AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE19="143388AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE20="144471AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE21="147874AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE22="148590AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE23="150308AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE24="151678AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE25="155756AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE26="156027AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE27="156119AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    public static final String CONVULSIVE28="161101AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
}
