package org.openmrs.module.financials;

public class HivDiagnosisConstants {
	
	public static final String HIV_0 = "823AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_1 = "1169AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_2 = "1215AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_3 = "1216AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_4 = "1217AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_5 = "5014AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_6 = "5015AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_7 = "5017AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_8 = "5020AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_9 = "5021AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_10 = "5022AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_11 = "5024AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_12 = "5028AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_13 = "5029AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_14 = "5032AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_15 = "5033AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_16 = "5034AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_17 = "5035AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_18 = "5037AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_19 = "5038AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_20 = "5040AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_21 = "5041AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_22 = "5043AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_23 = "5044AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_24 = "5048AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_25 = "5327AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_26 = "5329AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_27 = "5333AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_28 = "5338AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_29 = "5340AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_30 = "5344AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_31 = "5350AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_32 = "5354AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_33 = "110264AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_34 = "111061AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_35 = "129473AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_36 = "138405AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_37 = "138571AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_38 = "149741AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_39 = "153701AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_40 = "154234AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_41 = "154235AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_42 = "156667AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_43 = "156668AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_44 = "156669AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_45 = "156670AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_46 = "156671AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_47 = "156672AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_48 = "156673AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_49 = "159988AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_50 = "160158AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_51 = "160159AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_52 = "160160AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_53 = "160442AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_54 = "160443AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_55 = "160577AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_56 = "163324AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String HIV_57 = "163712AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
}
