package org.openmrs.module.financials;

public class MentalPalsyDiagnosisConstants {
	
	//mental Palsy
	public static final String PALSY1 = "112436AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY2 = "113136AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY3 = "113454AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY4 = "114388AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY5 = "115693AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY6 = "119395AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY7 = "119396AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY8 = "119750AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY9 = "121353AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY10 = "123006AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY11 = "124569AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY12 = "124572AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY13 = "124679AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY14 = "125035AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY15 = "126258AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY16 = "126839AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY17 = "128305AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY18 = "128442AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY19 = "128443AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY20 = "130738AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY21 = "130753AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY22 = "133748AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY23 = "137554AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY24 = "137978AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY25 = "138069AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY26 = "138959AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY27 = "139910AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY28 = "140815AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY29 = "140816AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY30 = "141085AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY31 = "141593AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY32 = "141625AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY33 = "143393AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY34 = "143633AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY35 = "143725AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY36 = "144091AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY37 = "145847AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY38 = "147031AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY39 = "147912AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY40 = "149550AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY41 = "149972AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY42 = "150895AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY43 = "152034AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY44 = "152484AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY45 = "152492AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY46 = "155483AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY47 = "155698AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY48 = "156626AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY49 = "158847AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
}
