package org.openmrs.module.financials;

public class MentalPalsyDiagnosisConstants {
	
	//mental Palsy
	public static final String PALSY1 = "112436AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY2 = "112437AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY3 = "112438AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY4 = "112439AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY5 = "112440AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY6 = "112441AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY7 = "112442AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY8 = "112443AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY9 = "112444AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY10 = "112445AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY11 = "112446AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY12 = "112447AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY13 = "112448AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY14 = "112449AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY15 = "112450AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY16 = "112451AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY17 = "112452AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY18 = "112453AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY19 = "112454AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY20 = "112455AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY21 = "112456AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY22 = "112457AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY23 = "112458AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY24 = "112459AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY25 = "112460AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY26 = "112461AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY27 = "112462AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY28 = "112463AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY29 = "112464AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY30 = "112465AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY31 = "112466AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY32 = "112467AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY33 = "112468AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY34 = "112469AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY35 = "112470AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY36 = "112471AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY37 = "112472AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY38 = "112473AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY39 = "112474AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY40 = "112475AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY41 = "112476AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY42 = "112477AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY43 = "112478AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY44 = "112479AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY45 = "112480AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY46 = "112481AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY47 = "112482AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY48 = "112483AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String PALSY49 = "112484AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
}
