package org.openmrs.module.financials;

public class OtherBitesDiagnosisConstants {
	
	public static final String OTHER_BITES1 = "168AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES2 = "1715AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES3 = "110534AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES4 = "111557AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES5 = "113936AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES6 = "113937AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES7 = "113940AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES8 = "114019AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES9 = "114060AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES10 = "114061AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES11 = "114795AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES12 = "114994AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES13 = "115141AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES14 = "115142AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES15 = "115143AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES16 = "116755AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES17 = "116756AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES18 = "116757AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES19 = "116758AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES20 = "116759AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES21 = "117004AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES22 = "117173AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES23 = "117484AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES24 = "117489AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES25 = "119760AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES26 = "121115AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES27 = "121116AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES28 = "121557AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES29 = "121561AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES30 = "121605AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES31 = "123213AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES32 = "123752AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES33 = "124538AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES34 = "124539AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES35 = "124670AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES36 = "125422AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES37 = "126210AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES38 = "126273AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES39 = "127886AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES40 = "127887AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES41 = "127902AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES42 = "127903AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES43 = "129590AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES44 = "129598AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES45 = "129609AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES46 = "129610AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES47 = "132685AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES48 = "132686AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES49 = "132687AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES50 = "132688AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES51 = "132689AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES52 = "132690AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES53 = "132691AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES54 = "132692AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES55 = "132693AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES56 = "132694AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES57 = "132696AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES58 = "132697AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES59 = "132698AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES60 = "132699AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES61 = "132700AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES62 = "132701AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES63 = "132702AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES64 = "132703AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES65 = "132704AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES66 = "132705AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES67 = "132706AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES68 = "132707AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES69 = "132708AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES70 = "132709AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES71 = "132710AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES72 = "132711AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES73 = "132712AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES74 = "132713AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES75 = "132714AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES76 = "132715AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES77 = "132716AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES78 = "132717AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES79 = "132718AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES80 = "132719AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES81 = "132721AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES82 = "132722AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES83 = "132723AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES84 = "132724AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES85 = "132725AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES86 = "132726AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES87 = "132727AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES88 = "132728AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES89 = "132729AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES90 = "132730AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES91 = "132731AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES92 = "132732AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES93 = "132733AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES94 = "132734AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES95 = "132735AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES96 = "132736AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES97 = "132737AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES98 = "132738AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES99 = "132739AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES100 = "132740AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES101 = "132741AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES102 = "132742AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES103 = "132743AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES104 = "132744AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES105 = "132745AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES106 = "132746AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES107 = "132747AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES108 = "132748AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES109 = "132749AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES110 = "132750AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES111 = "132751AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES112 = "132752AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES113 = "132753AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES114 = "132754AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES115 = "132755AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES116 = "132756AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES117 = "132757AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES118 = "132758AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES119 = "132759AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES120 = "132760AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES121 = "132761AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES122 = "132762AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES123 = "136797AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES124 = "136798AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES125 = "136801AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES126 = "136802AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES127 = "136807AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES128 = "136808AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES129 = "136810AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES130 = "136811AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES131 = "136812AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES132 = "136813AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES133 = "137129AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES134 = "137130AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES135 = "137131AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES136 = "137521AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES137 = "138412AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES138 = "139785AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES139 = "139786AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES140 = "139787AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES141 = "139788AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES142 = "139789AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES143 = "142821AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES144 = "145966AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES145 = "146087AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES146 = "146112AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES147 = "147268AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES148 = "147269AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES149 = "147272AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES150 = "147273AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES151 = "148295AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES152 = "148375AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES153 = "148754AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES154 = "148755AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES155 = "149085AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES156 = "152189AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES157 = "152190AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES158 = "152191AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES159 = "152192AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES160 = "152193AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES161 = "152194AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES162 = "152195AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES163 = "152196AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES164 = "152197AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES165 = "152198AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES166 = "152354AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES167 = "152355AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES168 = "152356AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES169 = "152385AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES170 = "152386AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES171 = "152387AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES172 = "152388AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES173 = "152389AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES174 = "152390AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES175 = "152391AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES176 = "155982AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES177 = "156308AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES178 = "156435AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES179 = "158027AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES180 = "158784AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES181 = "158788AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String OTHER_BITES182 = "162179AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
}
