package org.openmrs.module.financials;

public class RicketsDiagnosisConstants {
	
	//Rickets
	public static final String RICKETS1 = "111461AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String RICKETS2 = "112370AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String RICKETS3 = "119383AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String RICKETS4 = "119384AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String RICKETS5 = "123035AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String RICKETS6 = "123036AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String RICKETS7 = "127393AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String RICKETS8 = "127394AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String RICKETS9 = "129607AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String RICKETS10 = "129753AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String RICKETS11 = "130243AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String RICKETS12 = "133378AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String RICKETS13 = "136043AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String RICKETS14 = "136068AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String RICKETS15 = "139392AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String RICKETS16 = "142188AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String RICKETS17 = "146062AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String RICKETS18 = "146568AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String RICKETS19 = "148083AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String RICKETS20 = "149282AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	
	public static final String RICKETS21 = "158867AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
}
